### ISSUE TITLE
Persistent Bug - Run Experiment on Web Service.

### ISSUE THREAD

**Issue by omarzohdi** [CoEST/TraceLab#12]
The current version of Tracelab being converted to a web service has breaking bug. Currently upon running an experiment the web service version fails to run it while the Console version works correctly. There are subtle changes in code as seen in the following code snippet (ConosoleUI.cs).

![consoleui](https://cloud.githubusercontent.com/assets/10916957/14720683/49b72e32-07c8-11e6-8bc7-7064e07f3cc0.PNG)

The web service version works by passing a string to the parse line function and executing the application as if the command was input through the console. The following code snippets (TraceLab_UI.aspx.cs, Adaptor.cs) show the code flow from the web page to the previous code snippet (ConsoleUI.cs).

![tracelab_ui aspx cs](https://cloud.githubusercontent.com/assets/10916957/14721436/f5c7163a-07cb-11e6-951d-2e0b336ee3e0.png)
![adaptor](https://cloud.githubusercontent.com/assets/10916957/14721435/f5c35cc0-07cb-11e6-8f91-0e02b1eed44b.PNG)

The main bug manifests itself in the following code snippet (ExperimentRunner.cs) upon running the experiment the the m_runnableExperiment.IsEmpty flag returns a value of true. This Skips execution and returns an unsuccessful experiment run.

![experimentrunner](https://cloud.githubusercontent.com/assets/10916957/14721480/299e16d4-07cc-11e6-9603-b699ba55d873.PNG)

**Comment by omarzohdi** [comment]
While tracing the initial application execution, there's a discrepancy in the amount of components found in the directories by the initial component scan. The Following code snippet (TraceLabApplication.cs) shows the Component directories while running the application as a console application:
![componentdir_console](https://cloud.githubusercontent.com/assets/10916957/15161087/640e2aca-16c2-11e6-91ab-fb34d006496f.PNG)
The two directories are correct and seem to be loaded into the application correctly. While running application as a web service the result is the same as shown in the following code snippet (TraceLabApplication.cs):

![componentsdir_web](https://cloud.githubusercontent.com/assets/10916957/15162596/637d837e-16c9-11e6-956a-5708d2eaaabb.PNG)

However when scanning the actual components the number of components loaded in the applications seems to differ between the two versions. In the console application the number of components in the components collection is 88 as shown in the the following code snippet (TraceLabApplication.cs):

![componentcount_console](https://cloud.githubusercontent.com/assets/10916957/15161086/640c2c70-16c2-11e6-915c-0952a3f06d56.PNG)

While in the web application the number of components in the components collection is 6 as shown in the following code snippet (TraceLabApplication.cs):

![componentcount_web](https://cloud.githubusercontent.com/assets/10916957/15162595/6377f2ce-16c9-11e6-86ac-e682d60d0298.PNG)

This could be the cause of the experiment not running as the components essential for the experiment may be missing.

Note: The only difference between the two applications while debugging is that the TraceLab project and the TraceLabConsole project are both run as Libraries and not as a Window Application and Console application respectively

**Comment by omarzohdi** [comment]
Output Log files when Loading the Component Library on both versions of the application.

[ComponentLibraryOutput_Web.txt](https://github.com/CoEST/TraceLab/files/258311/ComponentLibraryOutput_Web.txt)
[ComponentLibraryOutput_Console.txt](https://github.com/CoEST/TraceLab/files/258312/ComponentLibraryOutput_Console.txt)

**Comment by omarzohdi** [comment]
There seems to be discrepancies in the scan method (ComponentScanner.cs) when loading components between the two versions. The number of directories loaded seem to be different. This could be the issue, or maybe it's nothing. I'm writing this comment as a quick reminded. More testing necessary.

![scanmethod](https://cloud.githubusercontent.com/assets/10916957/15342314/faf32caa-1c59-11e6-9d8d-2e5b0ae7238f.PNG)

**Comment by cebernalc** [comment]
Closing this issue since it will be handled in #17 with more information
