### ISSUE TITLE
how to get key file which running TraceLab need

### ISSUE THREAD

**Issue by cainiaofei** [CoEST/TraceLab#13]
![image](https://cloud.githubusercontent.com/assets/23117277/20047041/42c2c4ea-a4eb-11e6-8c9c-3136b0f094e3.png)

how to generate the key file, and the coest.org can't open.

**Comment by cebernalc** [comment]
You can download the one from this commit description https://github.com/CoEST/TraceLab/commit/f53ebc391976a870331242433570dc808cc75cdd it doesn't require any key
