### ISSUE TITLE
Both website are dead. How can we get the code for using TraceLab

### ISSUE THREAD

**Issue by DreambigOu** [CoEST/TraceLab#19]
Both website are dead. How can we get the code for using TraceLab?

For more information please visit the official project site: http://coest.org/ http://coest.org/coest-projects/projects/tracelab

For instructions how to compile (for now please use VisualStudio 2010): http://coest.org/coest-projects/projects/tracelab/wiki/Steps_to_compile_TraceLab

**Comment by cebernalc** [comment]
Hello, you can get the code here: https://github.com/CoEST/TraceLab/tree/master/Main and you can get the wiki info in #14

**Comment by DreambigOu** [comment]
Sorry, I mean the key file "tracelabkey.txt".
The file is required to start the tracelab. However, the website to request the key file is dead.
<img width="401" alt="screenshot 2017-06-15 11 41 24" src="https://user-images.githubusercontent.com/1847166/27192172-f3f38e9e-51bf-11e7-91b1-885316734119.png">

**Comment by cebernalc** [comment]
Try using the code from the branch TraceLabKeyRemoval, the key file will be removed in future versions.

**Comment by DreambigOu** [comment]
Hi, I tried executable files in bin folder from the latest version in the branch TraceLabKeyRemoval on both Windows and Mac OSX (mono is properly installed and environment configured).
The Tracelab program still reques a key file. 

Should I compile the code directly or is there any easy way to generate a key file? Thanks.

**Comment by cebernalc** [comment]
That should be working, anyway here is one key
[tracelabkey.txt](https://github.com/CoEST/TraceLab/files/1092063/tracelabkey.txt)
