### ISSUE TITLE
Multi-Platform Version - Placement of components on canvas

### ISSUE THREAD

**Issue by JaneClelandHuang** [CoEST/TraceLab#2]
When dragging a component onto the canvas it needs to be centered around the cursor.

**Comment by omarzohdi** [comment]
Done but needs testing on windows. Changes Shouldn't affect windows code. I'll test it when I get the chance.

**Comment by omarzohdi** [comment]
Minor Incompatibility issues with Windows version, fixing those before moving on.

**Comment by omarzohdi** [comment]
Breaks the WPF (obsolete) version but as long as its run on Mono - GTK it should be fine.
