### ISSUE TITLE
Cannot generate a tracelabkey

### ISSUE THREAD

**Issue by Blaiski** [CoEST/TraceLab#20]
Hi,
Can someone please guide me on how to get a valid tracelabkey.txt file? The official TraceLab page on coest.org is dead and cannot register for a license.

Thank you.
Mujtaba

**Comment by cebernalc** [comment]
Check this issue https://github.com/CoEST/TraceLab/issues/19

**Comment by Blaiski** [comment]
Thanks a lot cebernalc!
It worked finally. I used the key under #19 with the version under the branch TraceLabKeyRemoval. BTW, this version still requires the key!

![image](https://user-images.githubusercontent.com/31612240/30950715-275ed8e8-a47b-11e7-81c0-620845424385.png)
